apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-app-deployment
  labels:
    app: actions-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actions-app
  template:
    metadata:
      labels:
        app: actions-app
    spec:
      containers:
      - name: actions-app
        image: <image-location>/<image-repo>:latest
        ports:
        - containerPort: 3000

